### ISSUE TITLE
Witam mam problem z viaplay

### ISSUE THREAD

**Issue by rafalmar1981** [Mariusz89B/kodi-viaplay#9]
Dzień dobry. Jak w temacie, niedawno wszystko świetnie chodziło, a teraz wyskakuje błąd podczas uruchomienia jakiegoś filmu/serialu lub meczu bundesligi...tak to wygląda w logu:
https://paste.kodi.tv/ojilibovob
Czy da się to poprawić?

**Comment by Mariusz89B** [comment]
Witaj,

Korzystasz ze starej wersji wtyczki, wgraj wersje 2.3.4.
https://github.com/Mariusz89B/kodi-viaplay/releases/tag/2.3.4

**Comment by rafalmar1981** [comment]
Qrcze fajnie,że tak szybko odpowiedziałeś ale niestety nadal to samo
https://paste.kodi.tv/tisecakeja

**Comment by Mariusz89B** [comment]
Sprawdzałeś czy działa na Kodi v19? Wygląda mi to na błąd z szyfrowaniem w Kodi v18.

**Comment by rafalmar1981** [comment]
nie nie sprawdzałem, Niewiem czy dobrze kombinuję ale  jak przejdę na kodi 19 to wiele wtyczek mi nie będzie chodziło chodzi chyba coś o pythona czy tak??
ale zaraz sprawdzę na kompie

**Comment by zuzia-dev** [comment]
@rafalmar1981 ostatnia wersja 2.3.4 od @Mariusz89B działa prawidłowo pod Kodi 19, sprawdziłam na wszystkich trwających obecnie live i uruchamiają się poprawnie.
Jak chcesz możesz przetestować moją wersję: https://github.com/zuzia-dev/kodi-viaplay/releases/tag/v2.3.6 (Kodi 19) lub https://github.com/zuzia-dev/kodi-viaplay/archive/refs/heads/K18.zip (Kodi 18).
Przed chwilą sprawdzałam pod Androidem i obie działają jak powinny.

**Comment by rafalmar1981** [comment]
@Mariusz89B wersja 2.3.4 działa na win 7 kodi 19 miałeś rację ale nie chcę przechodzić na smarcie w 19 to zerknę od @zuzia-dev tę wersję na 18...za dużo wtyczek nie chodzi na 19
zaraz dam znać

**Comment by rafalmar1981** [comment]
@zuzia-dev https://github.com/zuzia-dev/kodi-viaplay/archive/refs/heads/K18.zip
nie działa na 18.9
log:
https://paste.kodi.tv/nusadepifi

**Comment by zuzia-dev** [comment]
@rafalmar1981 bez względu na to, z której wersji korzystasz, od @Mariusz89B czy mojej, usuń proszę wtyczkę wraz z danymi, zainstaluj ponownie i aktywuj dostęp przez https://viaplay.pl/activate

**Comment by rafalmar1981** [comment]
@zuzia-dev @Mariusz89B Dziękuję wam....jedna i druga działa, trzeba było usunąć dane i wszystko poleciało. Teraz na majówkę uciekajcie ja teraz jeszcze z canaleplus podzialam z hevet
